FROM mcr.microsoft.com/playwright:v1.58.2-noble
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Used to gracefully handle worker lifecycle if ran directly
CMD ["npm", "run", "start:worker"]
