/**
 * Kaizen — canonical shared types.
 *
 * These types are the source of truth for cross-module communication.
 * They are derived directly from the interface definitions in Section 6
 * of the master spec (docs/kaizen-spec-v2.md).
 *
 * Rule: no module imports another module's implementation.
 *       All cross-module data flows through these types.
 */

// ─── Test Compilation ────────────────────────────────────────────────────────

export type StepAction =
  | 'navigate'
  | 'click'
  | 'type'
  | 'select'
  | 'assert_visible'
  | 'wait'
  | 'press_key'
  | 'scroll';

export type StepAST = {
  action: StepAction;
  /** Natural language description of the target UI element. Null for navigate/wait. */
  targetDescription: string | null;
  /** The value to type, select, or key to press. Null when not applicable. */
  value: string | null;
  /** Target URL for navigate actions. */
  url: string | null;
  rawText: string;
  /** SHA-256(normalise(rawText)) — immutable identifier for this step version. Used for compiled_ast_cache. */
  contentHash: string;
  /**
   * SHA-256(action + ':' + (targetDescription ?? '')) — shared across all steps
   * that target the same element regardless of value.
   *
   * `type "test" in username` and `type "hello" in username` compile to different
   * contentHashes but the SAME targetHash because the element being targeted is
   * identical. The selector_cache uses targetHash as its lookup key so the second
   * step gets an instant cache hit and never calls the LLM resolver again.
   */
  targetHash: string;
};

// ─── DOM Pruning ─────────────────────────────────────────────────────────────

export type CandidateNode = {
  /** Execution tracking ID injected directly into the live DOM for zero-guesswork location */
  kaizenId?: string;
  role: string;
  /** Accessible name from the AX tree. */
  name: string;
  /**
   * Most stable selector for this element, used as the primary identifier.
   * Populated by the DOM pruner in priority order:
   *   1. role= ARIA selector (survives DOM restructuring)
   *   2. CSS id selector
   *   3. data-testid
   *   4. tag+name attribute
   *   5. tag+aria-label
   *   6. tag+placeholder
   *   7. data-kaizen-id (transient session fallback)
   */
  cssSelector: string;
  xpath: string;
  /** Center coordinates for Playwright native clicks */
  centerPoint?: { x: number; y: number };
  /** id, class, placeholder, aria-label, data-testid, etc. */
  attributes: Record<string, string>;
  textContent: string;
  isVisible: boolean;
  /** Pre-computed string similarity score against the step's targetDescription. */
  similarityScore: number;
  /**
   * All selectors for this element ordered from most stable to least stable.
   * Generated by the DOM pruner; used by the LLM as a ranked menu to pick from
   * and by the resolver as pre-validated fallbacks when LLM output fails.
   */
  selectorCandidates?: SelectorEntry[];
  /**
   * Nearest semantic ancestor label: <form aria-label>, <fieldset><legend>, or
   * closest <h1>–<h3> heading text. Used to disambiguate elements that share an
   * identical accessible name (e.g. two "Email" inputs on the same page).
   * Populated by PlaywrightDOMPruner; used only in LLM prompt formatting.
   */
  parentContext?: string;
};

// ─── Element Resolution ───────────────────────────────────────────────────────

export type SelectorStrategy = 'css' | 'xpath' | 'aria' | 'text' | 'data-testid';

export type SelectorEntry = {
  selector: string;
  strategy: SelectorStrategy;
  confidence: number;
};

/** Where a resolved selector came from — propagated to step_results for UI visibility. */
export type ResolutionSource = 'archetype' | 'redis' | 'db_exact' | 'pgvector_step' | 'pgvector_element' | 'llm';

/**
 * Compact snapshot of one DOM candidate as presented to the LLM.
 * Stored in step_results.dom_candidates for post-hoc debugging.
 */
export type CompactCandidate = {
  kaizenId: string;
  role: string;
  name: string;
  selector: string; // primary (most stable) selector
  /** Nearest semantic ancestor label — included when disambiguation was needed. */
  parentContext?: string;
};

export type SelectorSet = {
  selectors: SelectorEntry[];
  fromCache: boolean;
  cacheSource: 'tenant' | 'shared' | null;
  /** Which cache layer (or LLM) produced the selectors. */
  resolutionSource: ResolutionSource | null;
  /** Cosine similarity score when resolutionSource is a vector lookup; null otherwise. */
  similarityScore: number | null;
  /**
   * DOM candidates presented to the LLM for disambiguation.
   * Populated with the ranked list the LLM actually saw (post role-filter + score-rank).
   * Null on pure cache hits.
   */
  candidates?: CompactCandidate[];
  /** The kaizenId the LLM selected from those candidates. Null on cache hits. */
  llmPickedKaizenId?: string | null;
  /**
   * LLM tokens consumed during element resolution for this step.
   * Non-zero only when resolveElement was called (resolutionSource === 'llm').
   * Zero on all cache hits — no LLM was invoked.
   */
  tokensUsed?: number;
};

export type ResolutionContext = {
  tenantId: string;
  domain: string;
  /** Typed as unknown here; consuming modules import Page from playwright directly. */
  page: unknown;
  /**
   * Full URL of the current page at resolution time (e.g. "https://app.example.com/login").
   * Used to make element_embedding vectors page-context-aware so that two elements
   * with identical role+name on different pages (e.g. "textbox: Email" on /login vs
   * /register) produce distinct vectors and cannot cross-match via L2.5 pgvector search.
   */
  pageUrl?: string;
};

// ─── Accessibility tree ───────────────────────────────────────────────────────

/** Minimal AX tree node returned by Playwright's accessibility snapshot API. */
export type AXNode = {
  role: string;
  name?: string;
  children?: AXNode[];
};

// ─── Execution ────────────────────────────────────────────────────────────────

export type StepExecutionResult = {
  status: 'passed' | 'failed';
  selectorUsed: string | null;
  errorType: string | null;
  errorMessage: string | null;
  durationMs: number;
  screenshotKey: string | null;
  domSnapshotKey: string | null;
};

// ─── Healing ─────────────────────────────────────────────────────────────────

export type FailureClass =
  | 'ELEMENT_REMOVED'
  | 'ELEMENT_MUTATED'
  | 'ELEMENT_OBSCURED'
  | 'PAGE_NOT_LOADED'
  | 'TIMING'
  | 'LOGIC_FAILURE';

export type ClassifiedFailure = {
  stepResult: StepExecutionResult;
  /** DB id of the step_results row, if one was created for this execution. */
  stepResultId?: string;
  failureClass: FailureClass;
  step: StepAST;
  previousSelector: string;
};

export type HealingContext = {
  tenantId: string;
  runId: string;
  /** Typed as unknown here; consuming modules import Page from playwright directly. */
  page: unknown;
};

export type HealingAttempt = {
  succeeded: boolean;
  newSelector: string | null;
  durationMs: number;
};

export type HealingResult = {
  succeeded: boolean;
  strategyUsed: string;
  newSelector: string | null;
  attempts: number;
  durationMs: number;
};

// ─── LLM Gateway ─────────────────────────────────────────────────────────────

export type LLMResolutionResult = {
  selectors: SelectorEntry[];
  /** True if this response was served from the prompt hash cache — no tokens consumed. */
  fromCache: boolean;
  promptTokens: number;
  completionTokens: number;
  templateVersion: string;
  /** The kaizenId string the LLM returned, before we map it to selectors. */
  llmPickedKaizenId?: string | null;
  /** The exact ranked candidates that were shown to the LLM in the prompt. */
  llmPromptedCandidates?: CompactCandidate[];
};

// ─── Billing ─────────────────────────────────────────────────────────────────

export type BillingEventType =
  | 'LLM_CALL'
  | 'TEST_RUN_STARTED'
  | 'SCREENSHOT_STORED'
  | 'STORAGE_GB_DAY';

export type BillingEventInput = {
  tenantId: string;
  eventType: BillingEventType;
  quantity: number;
  unit: string;
  metadata?: Record<string, unknown>;
};

export type TenantUsage = {
  tenantId: string;
  month: string;
  llmTokens: number;
  testRuns: number;
  screenshotBytes: number;
  storageGbDays: number;
};

// ─── Observability ────────────────────────────────────────────────────────────

export type Span = {
  end(): void;
  setAttribute(key: string, value: string | number | boolean): void;
};

// ─── Database / Domain enums ──────────────────────────────────────────────────

export type PlanTier = 'starter' | 'growth' | 'enterprise';
export type RunStatus = 'queued' | 'running' | 'passed' | 'failed' | 'healed' | 'cancelled';
export type RunTrigger = 'web' | 'api' | 'cli' | 'schedule';
export type StepResultStatus = 'passed' | 'failed' | 'healed' | 'skipped';
export type KeyScope = 'read_only' | 'execute' | 'admin';
