/**
 * Kaizen — canonical shared types.
 *
 * These types are the source of truth for cross-module communication.
 * They are derived directly from the interface definitions in Section 6
 * of the master spec (docs/kaizen-spec-v2.md).
 *
 * Rule: no module imports another module's implementation.
 *       All cross-module data flows through these types.
 */

// ─── Test Compilation ────────────────────────────────────────────────────────

export type StepAction =
  // ── Navigation ──
  | 'navigate'
  | 'go_back'
  | 'go_forward'
  | 'reload'
  // ── Tab / window management ──
  | 'switch_tab'
  | 'close_tab'
  // ── Pointer interactions ──
  | 'click'
  | 'click_random'
  | 'double_click'
  | 'right_click'
  | 'hover'
  | 'drag_and_drop'
  // ── Form interactions ──
  | 'type'
  | 'clear'
  | 'select'
  | 'check'
  | 'uncheck'
  | 'upload'
  // ── Positive assertions ──
  | 'assert_visible'
  | 'assert_text'
  | 'assert_url'
  | 'assert_title'
  | 'assert_enabled'
  | 'assert_disabled'
  | 'assert_checked'
  | 'assert_not_checked'
  | 'assert_count'
  | 'assert_attribute'
  // ── Negative assertions ──
  | 'assert_not_visible'
  | 'assert_not_text'
  // ── Timing / keyboard / scroll ──
  | 'wait'
  | 'press_key'
  | 'scroll';

export type StepAST = {
  action: StepAction;
  /** Natural language description of the target UI element. Null for navigate/wait. */
  targetDescription: string | null;
  /** The value to type, select, or key to press. Null when not applicable. */
  value: string | null;
  /** Target URL for navigate actions. */
  url: string | null;
  rawText: string;
  /** SHA-256(normalise(rawText)) — immutable identifier for this step version. Used for compiled_ast_cache. */
  contentHash: string;
  /**
   * SHA-256(action + ':' + (targetDescription ?? '')) — shared across all steps
   * that target the same element regardless of value.
   *
   * `type "test" in username` and `type "hello" in username` compile to different
   * contentHashes but the SAME targetHash because the element being targeted is
   * identical. The selector_cache uses targetHash as its lookup key so the second
   * step gets an instant cache hit and never calls the LLM resolver again.
   */
  targetHash: string;
  /**
   * When set, after this step's action succeeds the worker stores the resolved
   * element's text into the run-scoped variable of this name, so a later step
   * can reference it via a `{{name}}` token. `click_random` sets this implicitly
   * (e.g. 'selectedItem'); any step may set it explicitly.
   * Spec: docs/specs/workers/spec-engine-capabilities-assert-random-capture.md §3.3
   */
  captureAs?: string | null;
  /**
   * 'delta' marks a DISCOVER ORACLE: an assertion about something the crawl
   * never saw, which therefore may only be resolved against what the previous
   * action CHANGED. Set by the Test Writer's canonical renderer for
   * description-target assertions; the worker enforces it, and an empty delta
   * fails the step instead of falling back to the whole page.
   * Spec: docs/specs/test-writer/spec-oracle-delta-and-fidelity.md §1
   */
  oracleScope?: 'delta' | null;
};

// ─── DOM Pruning ─────────────────────────────────────────────────────────────

export type CandidateNode = {
  /** Execution tracking ID injected directly into the live DOM for zero-guesswork location */
  kaizenId?: string;
  role: string;
  /** Accessible name from the AX tree. */
  name: string;
  /**
   * Most stable selector for this element, used as the primary identifier.
   * Populated by the DOM pruner in priority order:
   *   1. role= ARIA selector (survives DOM restructuring)
   *   2. CSS id selector
   *   3. data-testid
   *   4. tag+name attribute
   *   5. tag+aria-label
   *   6. tag+placeholder
   *   7. data-kaizen-id (transient session fallback)
   */
  cssSelector: string;
  xpath: string;
  /** Center coordinates for Playwright native clicks */
  centerPoint?: { x: number; y: number };
  /** id, class, placeholder, aria-label, data-testid, etc. */
  attributes: Record<string, string>;
  textContent: string;
  isVisible: boolean;
  /** Pre-computed string similarity score against the step's targetDescription. */
  similarityScore: number;
  /**
   * All selectors for this element ordered from most stable to least stable.
   * Generated by the DOM pruner; used by the LLM as a ranked menu to pick from
   * and by the resolver as pre-validated fallbacks when LLM output fails.
   */
  selectorCandidates?: SelectorEntry[];
  /**
   * Nearest semantic ancestor label: <form aria-label>, <fieldset><legend>, or
   * closest <h1>–<h3> heading text. Used to disambiguate elements that share an
   * identical accessible name (e.g. two "Email" inputs on the same page).
   * Populated by PlaywrightDOMPruner; used only in LLM prompt formatting.
   */
  parentContext?: string;
  /**
   * URL of the IFRAME this element lives in, when it was gathered from a child frame
   * (e.g. a third-party cookie-consent CMP). Undefined for main-document elements.
   * The execution engine locates + acts on the element WITHIN this frame.
   *
   * This is the LIVE url, query string and all. A CMP iframe's query carries
   * per-session tokens, so the cache stores its canonical origin + pathname instead.
   * See src/utils/frame-url.ts and spec-iframe-selector-caching.md.
   */
  frameUrl?: string;
};

// ─── Element Resolution ───────────────────────────────────────────────────────

export type SelectorStrategy = 'css' | 'xpath' | 'aria' | 'text' | 'data-testid';

export type SelectorEntry = {
  selector: string;
  strategy: SelectorStrategy;
  confidence: number;
};

/** Where a resolved selector came from — propagated to step_results for UI visibility. */
export type ResolutionSource =
  | 'archetype' | 'redis' | 'db_exact' | 'pgvector_step' | 'pgvector_element' | 'llm'
  /**
   * The delta oracle: the element was chosen from what the previous action
   * CHANGED, deterministically, no model call. Its own source so the run page
   * can say so instead of "this step did not need to find an element".
   * Spec: docs/specs/test-writer/spec-oracle-delta-and-fidelity.md §1
   */
  | 'delta';

/**
 * Compact snapshot of one DOM candidate as presented to the LLM.
 * Stored in step_results.dom_candidates for post-hoc debugging.
 */
export type CompactCandidate = {
  kaizenId: string;
  role: string;
  name: string;
  selector: string; // primary (most stable) selector
  /** Nearest semantic ancestor label — included when disambiguation was needed. */
  parentContext?: string;
};

export type SelectorSet = {
  selectors: SelectorEntry[];
  fromCache: boolean;
  cacheSource: 'tenant' | 'shared' | null;
  /** Which cache layer (or LLM) produced the selectors. */
  resolutionSource: ResolutionSource | null;
  /** Cosine similarity score when resolutionSource is a vector lookup; null otherwise. */
  similarityScore: number | null;
  /**
   * DOM candidates presented to the LLM for disambiguation.
   * Populated with the ranked list the LLM actually saw (post role-filter + score-rank).
   * Null on pure cache hits.
   */
  candidates?: CompactCandidate[];
  /** The kaizenId the LLM selected from those candidates. Null on cache hits. */
  llmPickedKaizenId?: string | null;
  /**
   * Second-target selectors for two-target actions (drag_and_drop): these locate
   * the DROP DESTINATION. `selectors` holds the drag SOURCE; these hold the target.
   * Populated by the worker's drag_and_drop routing; undefined for every other action.
   */
  destinationSelectors?: SelectorEntry[];
  /**
   * LLM tokens consumed during element resolution for this step.
   * Non-zero only when resolveElement was called (resolutionSource === 'llm').
   * Zero on all cache hits — no LLM was invoked.
   */
  tokensUsed?: number;
  /**
   * Archetype slug, populated only when resolutionSource === 'archetype'.
   * Persisted to step_results.archetype_name so the UI verdict route can write
   * an archetype_failures cooldown row from the API process (the resolver
   * instance that produced this match lives in the worker process).
   */
  archetypeName?: string | null;
  /**
   * URL of the IFRAME the resolved element lives in (from CandidateNode.frameUrl).
   * When set, the execution engine locates + acts within that frame instead of the
   * top document. Undefined for ordinary main-document elements.
   */
  frameUrl?: string;
};

export type ResolutionContext = {
  tenantId: string;
  domain: string;
  /** Typed as unknown here; consuming modules import Page from playwright directly. */
  page: unknown;
  /**
   * Full URL of the current page at resolution time (e.g. "https://app.example.com/login").
   * Used to make element_embedding vectors page-context-aware so that two elements
   * with identical role+name on different pages (e.g. "textbox: Email" on /login vs
   * /register) produce distinct vectors and cannot cross-match via L2.5 pgvector search.
   */
  pageUrl?: string;
  /**
   * Embedding of `"${step.action} ${step.targetDescription}"`, computed once per step
   * by CompositeElementResolver. Consumed by the cache layers both for existing
   * pgvector lookups (L3/L4) and for the semantic guard that rejects a cached hit
   * when its stored vectors disagree with the current step's intent (L1/L2/L3/L4).
   * Undefined when targetDescription is null (navigate/wait) — guard skipped.
   */
  stepEmbedding?: number[];
  /**
   * This resolution is happening on a behind-login page, so what it learns is
   * the tenant's private knowledge and must not leave the tenant. Suppresses
   * contribution to the SHARED selector pool (`is_shared`, `tenant_id NULL`),
   * which every other tenant on the same domain reads. The tenant's own
   * selector_cache write is unaffected — that is the tenant's memory of its own
   * app, and suppressing it would make authenticated tests permanently cold.
   *
   * The worker sets this from RunJobPayload.behindAuth; the Test Writer's
   * auth-session sets it for login-recipe execution during a crawl.
   * Spec: docs/specs/test-writer/spec-authenticated-scope.md §4.1
   */
  behindAuth?: boolean;
};

/**
 * Run-scoped key/value memory threaded through the step loop. Steps capture
 * values into it (via StepAST.captureAs) and reference them in later steps via
 * `{{name}}` tokens in value/targetDescription. Lives only for the duration of
 * one run in worker memory; captured values are persisted per-step in
 * step_results for the run details page.
 * Spec: docs/specs/workers/spec-engine-capabilities-assert-random-capture.md §3.2
 */
export type RunContext = {
  variables: Record<string, string>;
};

// ─── Accessibility tree ───────────────────────────────────────────────────────

/** Minimal AX tree node returned by Playwright's accessibility snapshot API. */
export type AXNode = {
  role: string;
  name?: string;
  children?: AXNode[];
};

// ─── Execution ────────────────────────────────────────────────────────────────

export type StepExecutionResult = {
  status: 'passed' | 'failed';
  selectorUsed: string | null;
  errorType: string | null;
  errorMessage: string | null;
  durationMs: number;
  screenshotKey: string | null;
  domSnapshotKey: string | null;
};

// ─── Healing ─────────────────────────────────────────────────────────────────

export type FailureClass =
  | 'ELEMENT_REMOVED'
  | 'ELEMENT_MUTATED'
  | 'ELEMENT_OBSCURED'
  | 'PAGE_NOT_LOADED'
  | 'TIMING'
  | 'LOGIC_FAILURE';

export type ClassifiedFailure = {
  stepResult: StepExecutionResult;
  /** DB id of the step_results row, if one was created for this execution. */
  stepResultId?: string;
  failureClass: FailureClass;
  step: StepAST;
  previousSelector: string;
};

export type HealingContext = {
  tenantId: string;
  runId: string;
  /** Typed as unknown here; consuming modules import Page from playwright directly. */
  page: unknown;
};

export type HealingAttempt = {
  succeeded: boolean;
  newSelector: string | null;
  durationMs: number;
};

export type HealingResult = {
  succeeded: boolean;
  strategyUsed: string;
  newSelector: string | null;
  attempts: number;
  durationMs: number;
};

// ─── LLM Gateway ─────────────────────────────────────────────────────────────

export type LLMResolutionResult = {
  selectors: SelectorEntry[];
  /** True if this response was served from the prompt hash cache — no tokens consumed. */
  fromCache: boolean;
  promptTokens: number;
  completionTokens: number;
  templateVersion: string;
  /** The kaizenId string the LLM returned, before we map it to selectors. */
  llmPickedKaizenId?: string | null;
  /** The exact ranked candidates that were shown to the LLM in the prompt. */
  llmPromptedCandidates?: CompactCandidate[];
};

// ─── Billing ─────────────────────────────────────────────────────────────────

export type BillingEventType =
  | 'LLM_CALL'
  | 'TEST_RUN_STARTED'
  | 'SCREENSHOT_STORED'
  | 'STORAGE_GB_DAY';

export type BillingEventInput = {
  tenantId: string;
  eventType: BillingEventType;
  quantity: number;
  unit: string;
  metadata?: Record<string, unknown>;
};

export type TenantUsage = {
  tenantId: string;
  month: string;
  llmTokens: number;
  testRuns: number;
  screenshotBytes: number;
  storageGbDays: number;
};

// ─── Observability ────────────────────────────────────────────────────────────

export type Span = {
  end(): void;
  setAttribute(key: string, value: string | number | boolean): void;
};

// ─── Database / Domain enums ──────────────────────────────────────────────────

export type PlanTier = 'starter' | 'growth' | 'enterprise';
export type RunStatus = 'queued' | 'running' | 'passed' | 'failed' | 'healed' | 'cancelled';
export type RunTrigger = 'web' | 'api' | 'cli' | 'schedule';
export type StepResultStatus = 'passed' | 'failed' | 'healed' | 'skipped';
export type KeyScope = 'read_only' | 'execute' | 'admin';
